describe('Midi Message', function()
  it('creates a new instance', function()
    local message = Midi.Message(Midi.Type.NoteOn, 60, 120, 1)
    expect(message.type):toBe(Midi.Type.NoteOn)
    expect(message.note):toBe(60)
    expect(message.velocity):toBe(120)
    expect(message.channel):toBe(1)
  end)

  it('creates a new instance from bytes', function()
    local message = Midi.Message:fromBytes(24657040)
    expect(message.type):toBe(Midi.Type.NoteOn)
    expect(message.note):toBe(60)
    expect(message.velocity):toBe(120)
    expect(message.channel):toBe(1)
  end)

  it('serializes to bytes', function()
    local message = Midi.Message(Midi.Type.NoteOn, 60, 120, 1)
    expect(message:toBytes()):toBe(24657040)
  end)

  it('provides shorthands', function()
    expect(Midi.NoteOn():is(Midi.Type.NoteOn)):toBe(true)
    expect(Midi.NoteOff():is(Midi.Type.NoteOff)):toBe(true)
    expect(Midi.ControlChange():is(Midi.Type.ControlChange)):toBe(true)
  end)
end)
